version: 2
services:
  strapi:
    source: ./backend
    build:
      command: npm install && npm run build
      watchPatterns:
        - backend/**
    start:
      command: npm start
    healthcheck:
      command: "curl -f http://localhost:$PORT/admin || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
    variables:
      NODE_ENV: production
      DATABASE_CLIENT: postgres
      DATABASE_SSL: true
    # Railway will automatically provide PostgreSQL database