$schema: https://railway.app/railway.schema.json
version: 2
services:
  web:
    source: ./backend
    build:
      command: npm ci && npm run build
    start:
      command: npm run start
    variables:
      NODE_ENV: production