/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    menu: Menu;
    pages: Page;
    footer: Footer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    menu: MenuSelect<false> | MenuSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Admin: full access, Editor: can create/edit, Viewer: read-only
   */
  role: 'admin' | 'editor' | 'viewer';
  /**
   * Full name of the user
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
  | {
    id: string;
    createdAt?: string | null;
    expiresAt: string;
  }[]
  | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu".
 */
export interface Menu {
  id: string;
  /**
   * Menu item text (e.g., "Home", "About", "Contact")
   */
  label: string;
  /**
   * URL or path (e.g., "/", "/about", "https://example.com")
   */
  url: string;
  /**
   * Order of appearance in menu (lower number = appears first)
   */
  order: number;
  /**
   * Open link in new tab
   */
  openInNewTab?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Page title (e.g., "O nas", "Kontakt")
   */
  title: string;
  /**
   * URL slug - auto-generated from title if left empty (Polish chars converted)
   */
  slug: string;
  /**
   * Mark this page as the homepage (displayed at "/")
   */
  isHomepage?: boolean | null;
  status: 'draft' | 'published';
  blocks?:
  | (
    | {
      heading: string;
      subheading?: string | null;
      backgroundImage?: (string | null) | Media;
      id?: string | null;
      blockName?: string | null;
      blockType: 'hero';
    }
    | {
      text: string;
      id?: string | null;
      blockName?: string | null;
      blockType: 'content';
    }
  )[]
  | null;
  /**
   * Available only on the homepage – controls the 3-column cards layout.
   */
  homepageColumns?: {
    /**
     * Optional heading displayed above the columns.
     */
    title?: string | null;
    cards?:
    | {
      Enumeration: 'Block_BigText' | 'Block_DescText' | 'Block_Video' | 'Block_Image';
      size: 'small' | 'medium' | 'large';
      titleLine1?: string | null;
      titleLine2?: string | null;
      subtitle?: string | null;
      subtitleColor?: ('red' | 'blue' | 'green') | null;
      titleColor?: ('red' | 'blue' | 'green') | null;
      title?: string | null;
      description?: string | null;
      category?: string | null;
      imageSrc?: (string | null) | Media;
      imageAlt?: string | null;
      videoWebm?: (string | null) | Media;
      videoMp4?: (string | null) | Media;
      footerTitle?: string | null;
      footerDescription?: string | null;
      buttonText?: string | null;
      buttonColor?: ('red' | 'blue' | 'green') | null;
      buttonLinkType?: ('none' | 'external' | 'internal') | null;
      buttonLinkValue?: string | null;
      id?: string | null;
    }[]
    | null;
  };
  seo?: {
    /**
     * SEO title (optional, defaults to page title)
     */
    metaTitle?: string | null;
    /**
     * SEO meta description
     */
    metaDescription?: string | null;
    /**
     * SEO share image (optional)
     */
    metaImage?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Global footer configuration - appears on all pages
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * Internal title for admin panel
   */
  title: string;
  /**
   * Company name displayed in footer
   */
  companyName: string;
  /**
   * Short company description or tagline
   */
  description?: string | null;
  address?: {
    street?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
  };
  socialMedia?:
  | {
    platform: 'facebook' | 'instagram' | 'linkedin' | 'twitter' | 'youtube' | 'tiktok';
    /**
     * Full URL to social media profile
     */
    url: string;
    id?: string | null;
  }[]
  | null;
  /**
   * Footer navigation links
   */
  links?:
  | {
    label: string;
    /**
     * Internal path (e.g., /about) or external URL
     */
    url: string;
    id?: string | null;
  }[]
  | null;
  /**
   * Copyright notice (e.g., "© 2025 Company Name. All rights reserved.")
   */
  copyrightText?: string | null;
  /**
   * Footer logo (optional)
   */
  logo?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
  | {
    [k: string]: unknown;
  }
  | unknown[]
  | string
  | number
  | boolean
  | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
  | ({
    relationTo: 'users';
    value: string | User;
  } | null)
  | ({
    relationTo: 'media';
    value: string | Media;
  } | null)
  | ({
    relationTo: 'menu';
    value: string | Menu;
  } | null)
  | ({
    relationTo: 'pages';
    value: string | Page;
  } | null)
  | ({
    relationTo: 'footer';
    value: string | Footer;
  } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
  | {
    [k: string]: unknown;
  }
  | unknown[]
  | string
  | number
  | boolean
  | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
  | T
  | {
    id?: T;
    createdAt?: T;
    expiresAt?: T;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu_select".
 */
export interface MenuSelect<T extends boolean = true> {
  label?: T;
  url?: T;
  order?: T;
  openInNewTab?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isHomepage?: T;
  status?: T;
  blocks?:
  | T
  | {
    hero?:
    | T
    | {
      heading?: T;
      subheading?: T;
      backgroundImage?: T;
      id?: T;
      blockName?: T;
    };
    content?:
    | T
    | {
      text?: T;
      id?: T;
      blockName?: T;
    };
  };
  homepageColumns?:
  | T
  | {
    title?: T;
    cards?:
    | T
    | {
      Enumeration?: T;
      size?: T;
      titleLine1?: T;
      titleLine2?: T;
      subtitle?: T;
      subtitleColor?: T;
      titleColor?: T;
      title?: T;
      description?: T;
      category?: T;
      imageSrc?: T;
      imageAlt?: T;
      videoWebm?: T;
      videoMp4?: T;
      footerTitle?: T;
      footerDescription?: T;
      buttonText?: T;
      buttonColor?: T;
      buttonLinkType?: T;
      buttonLinkValue?: T;
      id?: T;
    };
  };
  seo?:
  | T
  | {
    metaTitle?: T;
    metaDescription?: T;
    metaImage?: T;
  };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  title?: T;
  companyName?: T;
  description?: T;
  address?:
  | T
  | {
    street?: T;
    city?: T;
    postalCode?: T;
    country?: T;
  };
  contact?:
  | T
  | {
    email?: T;
    phone?: T;
  };
  socialMedia?:
  | T
  | {
    platform?: T;
    url?: T;
    id?: T;
  };
  links?:
  | T
  | {
    label?: T;
    url?: T;
    id?: T;
  };
  copyrightText?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config { }
}